#!/usr/bin/env bash
#BSUB -J mtl_all_ds
#BSUB -q standard
#BSUB -n 4
#BSUB -M 16000
#BSUB -W 24:00
#BSUB -R "span[hosts=1] rusage[mem=16000]"
#BSUB -o logs/11_all_ds.%J.out
#BSUB -e logs/11_all_ds.%J.err

set -euo pipefail
cd /home/ijonsdot/ilmur/mtlA_survey/New_test

source activate software-bundle

bash scripts/07_make_mannitol_db.sh
bash scripts/08_blast_mannitol_downsampled.sh
bash scripts/09_summarize_presence.sh
python scripts/10_species_prevalence.py
